language: go
sudo: false

matrix:
  include:
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - go get -t -v ./...
  - go get github.com/go-playground/overalls
  - go install github.com/go-playground/overalls

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -race ./...
  - overalls -project=github.com/usmanhalalit/gost  -covermode=count
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN