language: go
sudo: false

matrix:
  include:
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN